services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      STRIPE_SECRET_KEY: "sK_Live_51RJdg0GVRhUKYSLZN2Ij5TeYu9iGEFpzvIIE6IEjnag6G15zJM0Xm5C00CJpiSgRvano1BaoPgSCrW70SI1VZ0j80yWFIbPs0"

  db:
    image: mysql:5.7.43  # Use exact version
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_DATABASE: ecommerceweb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DATABASE FILE/ecommerceweb.sql:/docker-entrypoint-initdb.d/ecommerceweb.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1  # Use exact version
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: