version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - "8000:80"  # ✅ Port 8000 is free
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql57_custom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: larbi
      MYSQL_PASSWORD: larbi123
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3308:3306"  # ✅ Avoids conflicts with existing MySQL containers
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_custom
    restart: always
    ports:
      - "8081:80"  # ✅ 8080 is in use; 8081 is free
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: larbi
      PMA_PASSWORD: larbi123
    depends_on:
      - db

volumes:
  db_data:

